import React from "react";
import { ArrowRight, Edit3 } from "lucide-react";
import { useNavigate } from "react-router-dom";

const StoryPreviewCard = ({ language = "en" }) => {
  const navigate = useNavigate();

  const translations = {
    en: {
      title: "How the World Sees Your Story",
      storyPreview:
        "Meet Rajesh Kumar, a master craftsman from the vibrant village of Hoshiarpur. For over two decades, he has been weaving magic into traditional Punjabi textiles, carrying forward the legacy of his forefathers. Each piece tells a story of dedication, skill, and the rich cultural heritage of Punjab...",
      viewEdit: "View & Edit Story",
      generatedBy: "Generated by KalaKriti AI",
    },
    pa: {
      title: "ਸੰਸਾਰ ਤੁਹਾਡੀ ਕਹਾਣੀ ਨੂੰ ਕਿਵੇਂ ਦੇਖਦਾ ਹੈ",
      storyPreview:
        "ਰਾਜੇਸ਼ ਕੁਮਾਰ ਨੂੰ ਮਿਲੋ, ਹੁਸ਼ਿਆਰਪੁਰ ਦੇ ਜੀਵੰਤ ਪਿੰਡ ਤੋਂ ਇੱਕ ਮਾਹਿਰ ਕਾਰੀਗਰ। ਦੋ ਦਹਾਕਿਆਂ ਤੋਂ ਵੱਧ ਸਮੇਂ ਤੋਂ, ਉਹ ਰਵਾਇਤੀ ਪੰਜਾਬੀ ਕੱਪੜਿਆਂ ਵਿੱਚ ਜਾਦੂ ਬੁਣ ਰਿਹਾ ਹੈ, ਆਪਣੇ ਪੁਰਖਿਆਂ ਦੀ ਵਿਰਾਸਤ ਨੂੰ ਅੱਗੇ ਵਧਾ ਰਿਹਾ ਹੈ...",
      viewEdit: "ਕਹਾਣੀ ਦੇਖੋ ਅਤੇ ਸੰਪਾਦਿਤ ਕਰੋ",
      generatedBy: "ਕਲਾਕ੍ਰਿਤੀ AI ਦੁਆਰਾ ਤਿਆਰ",
    },
  };

  const t = translations[language];

  return (
    <div className="bg-gradient-to-br from-purple-50 to-pink-50 rounded-xl border border-purple-100 p-6 hover:shadow-md transition-all duration-200">
      <div className="flex items-start justify-between mb-4">
        <h3 className="text-lg font-semibold text-gray-900">{t.title}</h3>
        <div className="w-8 h-8 bg-purple-100 rounded-lg flex items-center justify-center">
          <Edit3 size={16} className="text-purple-600" />
        </div>
      </div>

      <div className="mb-4">
        <p className="text-gray-600 leading-relaxed line-clamp-4">
          {t.storyPreview}
        </p>
      </div>

      <div className="flex items-center justify-between">
        <span className="text-xs text-purple-600 font-medium">
          {t.generatedBy}
        </span>

        <button
          onClick={() => navigate("/profile")}
          className="flex items-center space-x-2 text-purple-600 hover:text-purple-700 font-medium text-sm transition-colors group"
        >
          <span>{t.viewEdit}</span>
          <ArrowRight
            size={16}
            className="group-hover:translate-x-1 transition-transform"
          />
        </button>
      </div>
    </div>
  );
};

export default StoryPreviewCard;
